// packages/ui-angular/src/examples/blocks/profile-form.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { KxButton } from '../../lib/button';
import { KxCard, KxCardContent, KxCardDescription, KxCardFooter, KxCardHeader, KxCardTitle, KxInput, KxSeparator } from '../../lib/primitives';
import { KxAvatar, KxAvatarFallback } from '../../lib/display';
import { KxField, KxFieldDescription, KxFieldLabel, KxRadio, KxRadioGroup, KxTextarea } from '../../lib/forms';

/**
 * The "Profile form" block — see sign-in.ts for how block fixtures work.
 *
 * A radio group rather than a select: three mutually exclusive choices whose consequences differ, so all
 * three should be readable at once instead of hidden behind a closed control. `kx-radio` renders a real
 * `<input type="radio">` with a `<label for>`, which is what gives the group arrow-key navigation and makes
 * each whole row a click target.
 *
 * The group sits in a `<fieldset>` with a `<legend>`, so a screen reader announces "Who can see your profile"
 * before each option. Without it the three options are just three unrelated radios.
 */
// kx-block:start
@Component({
  selector: 'app-profile-form-block',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    KxAvatar, KxAvatarFallback, KxButton, KxCard, KxCardContent, KxCardDescription, KxCardFooter,
    KxCardHeader, KxCardTitle, KxField, KxFieldDescription, KxFieldLabel, KxInput, KxRadio, KxRadioGroup,
    KxSeparator, KxTextarea,
  ],
  template: `
    <kx-card>
      <kx-card-header>
        <kx-card-title>Profile</kx-card-title>
        <kx-card-description>This is how you appear to other people.</kx-card-description>
      </kx-card-header>
      <kx-card-content class="body">
        <div class="identity">
          <kx-avatar class="photo">
            <kx-avatar-fallback>ZF</kx-avatar-fallback>
          </kx-avatar>
          <div class="identity-actions">
            <button kxButton variant="Outline" size="sm">Change photo</button>
            <span class="hint">JPG or PNG, up to 2&nbsp;MB.</span>
          </div>
        </div>

        <kx-field>
          <label kxFieldLabel for="pf-name">Display name</label>
          <input kxInput id="pf-name" autocomplete="name" value="Ziad Fteha" />
        </kx-field>

        <kx-field>
          <label kxFieldLabel for="pf-bio">Bio</label>
          <textarea kxTextarea id="pf-bio" rows="3">Building a five-platform design system.</textarea>
          <span kxFieldDescription>Shown under your name. Plain text.</span>
        </kx-field>

        <kx-separator />

        <fieldset class="visibility">
          <legend>Who can see your profile</legend>
          <kx-radio-group [(value)]="visibility">
            @for (option of options; track option.value) {
              <span class="option">
                <kx-radio [value]="option.value">{{ option.label }}</kx-radio>
                <span class="hint">{{ option.hint }}</span>
              </span>
            }
          </kx-radio-group>
        </fieldset>
      </kx-card-content>
      <kx-card-footer class="actions">
        <button kxButton variant="Ghost">Cancel</button>
        <button kxButton>Save changes</button>
      </kx-card-footer>
    </kx-card>
  `,
  styles: `
    :host { display: block; max-inline-size: 32rem; }
    .body { display: grid; gap: var(--spacing-6); }
    .identity { display: flex; align-items: center; gap: var(--spacing-4); }
    .photo { inline-size: 3.5rem; block-size: 3.5rem; }
    .identity-actions { display: grid; gap: var(--spacing-1); justify-items: start; }
    .hint { font: var(--text-body-sm); color: hsl(var(--muted-foreground)); }
    .visibility { margin: 0; padding: 0; border: 0; }
    .visibility legend { margin-block-end: var(--spacing-3); font: var(--text-label-sm); color: hsl(var(--foreground)); }
    .option { display: grid; gap: var(--spacing-1); }
    .option + .option { margin-block-start: var(--spacing-3); }
    .actions { display: flex; justify-content: flex-end; gap: var(--spacing-2); }
  `,
})
export class ProfileFormBlock {
  readonly visibility = signal('team');

  readonly options = [
    { value: 'everyone', label: 'Everyone', hint: 'Anyone with the link can see your profile.' },
    { value: 'team', label: 'Only my team', hint: 'People in your workspace.' },
    { value: 'nobody', label: 'Nobody', hint: 'Your profile stays hidden.' },
  ];
}
// kx-block:end

// apps/web/src/examples/blocks/profile-form.tsx
"use client";

import * as React from "react";
import {
  Avatar,
  AvatarFallback,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
  Field,
  FieldDescription,
  FieldLabel,
  Input,
  Label,
  RadioGroup,
  RadioGroupItem,
  Separator,
  Textarea,
} from "@kinetixui/ui";

// kx-block:start
const VISIBILITY = [
  { value: "everyone", label: "Everyone", hint: "Anyone with the link can see your profile." },
  { value: "team", label: "Only my team", hint: "People in your workspace." },
  { value: "nobody", label: "Nobody", hint: "Your profile stays hidden." },
];

export function ProfileFormBlock() {
  const [visibility, setVisibility] = React.useState("team");

  return (
    <Card className="w-full max-w-lg">
      <CardHeader>
        <CardTitle>Profile</CardTitle>
        <CardDescription>This is how you appear to other people.</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-6">
        <div className="flex items-center gap-4">
          <Avatar className="size-14">
            <AvatarFallback>ZF</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <Button variant="Outline" size="sm" className="w-fit">
              Change photo
            </Button>
            <p className="text-xs text-muted-foreground">JPG or PNG, up to 2&nbsp;MB.</p>
          </div>
        </div>
        <Field>
          <FieldLabel htmlFor="pf-name">Display name</FieldLabel>
          <Input id="pf-name" defaultValue="Ziad Fteha" autoComplete="name" />
        </Field>
        <Field>
          <FieldLabel htmlFor="pf-bio">Bio</FieldLabel>
          <Textarea id="pf-bio" rows={3} defaultValue="Building a five-platform design system." />
          <FieldDescription>Shown under your name. Plain text.</FieldDescription>
        </Field>
        <Separator />
        {/*
          A radio group, not a select: three mutually exclusive choices whose consequences differ, so they
          should all be readable at once rather than hidden behind a closed control.
        */}
        <fieldset className="grid gap-3">
          <legend className="mb-3 text-sm font-medium">Who can see your profile</legend>
          <RadioGroup value={visibility} onValueChange={setVisibility} className="grid gap-3">
            {VISIBILITY.map((option) => (
              <div key={option.value} className="flex items-start gap-3">
                <RadioGroupItem id={`pf-${option.value}`} value={option.value} className="mt-0.5" />
                <div className="grid gap-0.5">
                  <Label htmlFor={`pf-${option.value}`} className="font-normal">
                    {option.label}
                  </Label>
                  <span className="text-xs text-muted-foreground">{option.hint}</span>
                </div>
              </div>
            ))}
          </RadioGroup>
        </fieldset>
      </CardContent>
      <CardFooter className="justify-end gap-2">
        <Button variant="Ghost">Cancel</Button>
        <Button>Save changes</Button>
      </CardFooter>
    </Card>
  );
}
// kx-block:end
